# Generated by Django 3.2.9 on 2021-12-08 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_movie_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='draft',
            field=models.BooleanField(default=False, verbose_name='Черновик'),
        ),
    ]
