# Generated by Django 3.2.9 on 2021-12-08 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_genre_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='year',
            field=models.PositiveSmallIntegerField(default=2021, verbose_name='Дата выхода'),
        ),
    ]
