# Generated by Django 3.2.9 on 2021-12-08 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_genre_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='draft',
        ),
        migrations.RemoveField(
            model_name='genre',
            name='year',
        ),
    ]
